apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scale-up
  namespace: scaler
spec:
  schedule: "0,5,10,15,20,25,30,35,40,45,50,55  * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: Never
            args:
              - patch
              - hpa
              - php-apache
              - -p {"spec":{"minReplicas":10}}
          serviceAccountName: scaler-service-account
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scale-down
  namespace: scaler
spec:
  schedule: "2,7,12,17,22,27,32,37,42,47,52,57  * * * *" 
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            imagePullPolicy: Never
            args:
              - patch
              - hpa
              - php-apache
              - -p {"spec":{"minReplicas":1}}
          serviceAccountName: scaler-service-account